apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: worker
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: kodekloud/examplevotingapp_worker
        name: worker