apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: worker
  namespace: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: kodekloud/examplevotingapp_worker
        name: worker